stages:
  - build-dotnet
  - test-dotnet
  - build-mono
  - test-mono

build-dotnet:
  stage: build-dotnet
  # image: mcr.microsoft.com/dotnet/sdk:6.0
  image: microsoft/dotnet-framework:4.6.2
  
  before_script:
    - "dotnet restore ./FilmCollection.sln"
  script:
      - "dotnet build ./FilmCollection.sln"

build-mono:
  stage: build-mono
  image: mono:latest
  script:
    - nuget restore ./FilmCollection.sln
    - msbuild 
        /p:Configuration="Release"
        /p:Platform="Any CPU" 
        "./FilmCollection.sln"
