language: csharp
solution: FilmCollection.sln
dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-1-003177
os: Visual Studio 2015
branches:
  only:
    - master
install:
  - nuget restore FilmCollection.sln
