version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Debug
platform: Any CPU
before_build:
- ps: Import-PfxCertificate -FilePath C:\projects\filmcollection\FCkey.pfx
build:
  project: FilmCollection.sln
  verbosity: minimal